# Generated by Django 4.2 on 2023-04-25 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(primary_key=True, serialize=False, unique=True),
                ),
                ("product_name", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("employees", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Организация",
                "verbose_name_plural": "Организации",
                "db_table": "organizations",
            },
        ),
        migrations.CreateModel(
            name="Requisites",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("name", "name"),
                            ("inn", "inn"),
                            ("kpp", "kpp"),
                            ("ogrn", "ogrn"),
                        ],
                        max_length=15,
                    ),
                ),
                ("value", models.CharField(max_length=100)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requisites",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Реквизит",
                "verbose_name_plural": "Реквизиты",
                "db_table": "requisites",
                "unique_together": {("organization", "name")},
            },
        ),
    ]
