# Generated by Django 4.2 on 2023-04-24 02:05
import uuid
from datetime import datetime, timedelta

import jwt
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def create_token(apps, schema_editor):
    Token = apps.get_model("tokens", "Token")
    now = datetime.now(tz=timezone.utc)
    payload = {
        "exp": now + timedelta(seconds=settings.JWT_EXPIRED),
    }
    secret = uuid.uuid4().hex
    Token.objects.create(
        jwt=jwt.encode(payload, secret, algorithm=settings.JWT_ALGORITHM), secret=secret
    )


def remove_token(apps, schema_editor):
    Token = apps.get_model("tokens", "Token")
    Token.objects.all().delete()


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jwt", models.CharField(max_length=150)),
                ("secret", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Ключ",
                "verbose_name_plural": "Ключи",
                "db_table": "tokens",
            },
        ),
        migrations.RunPython(create_token, remove_token),
    ]
